// Mock data for WalTube app development
// This simulates Firebase data structures
import {
  availableModels,
  availableMoodLabels,
  availableStyleTags,
  Collection,
  difficultyLevels,
  Notification,
  Prompt,
  User,
  Workflow,
} from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    uid: 'user1',
    handle: 'soramaster',
    displayName: 'Alex Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHdvbWFufGVufDF8fHx8MTc3NTM3OTAyOXww&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'AI video creator specializing in cinematic aerial shots',
    links: { x: '@alexchen', instagram: 'alexchen', youtube: 'alexchen' },
    primaryModels: ['Sora', 'Runway'],
    followers: 12500,
    following: 340,
    totalCopies: 4200,
    totalPrompts: 87,
    createdAt: new Date('2024-01-15'),
  },
  {
    uid: 'user2',
    handle: 'runwaypro',
    displayName: 'Jordan Rivera',
    avatarUrl: 'https://images.unsplash.com/photo-1554765345-6ad6a5417cde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMG1hbnxlbnwxfHx8fDE3NzUzNjAyNDB8MA&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'Experimental video artist pushing AI boundaries',
    links: { instagram: 'jordanrivera', website: 'jordanrivera.com' },
    primaryModels: ['Runway', 'Kling', 'Pika'],
    followers: 8900,
    following: 210,
    totalCopies: 2800,
    totalPrompts: 63,
    createdAt: new Date('2024-02-01'),
  },
  {
    uid: 'currentUser',
    handle: 'yourhandle',
    displayName: 'Your Name',
    avatarUrl: 'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHdvbWFufGVufDF8fHx8MTc3NTM3OTAyOXww&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'AI video enthusiast exploring creative prompts',
    links: {},
    primaryModels: ['Sora'],
    followers: 342,
    following: 125,
    totalCopies: 89,
    totalPrompts: 12,
    createdAt: new Date('2024-03-10'),
  },
];

// Mock Prompts
export const mockPrompts: Prompt[] = [
  {
    id: 'prompt1',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video1.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635255073378-ac341396271b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaW5lbWF0aWMlMjBkcm9uZSUyMGFlcmlhbCUyMGxhbmRzY2FwZXxlbnwxfHx8fDE3NzU0NDAwMDh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'A sweeping aerial view of a misty mountain valley at golden hour, slow smooth camera movement pushing forward through low-hanging clouds revealing a winding river below, cinematic depth of field, warm color grading',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['cinematic', 'aerial', 'nature'],
    cameraNotes: 'anamorphic lens, slow dolly forward, shallow depth of field',
    moodLabel: 'Cinematic',
    difficulty: 'Intermediate',
    likes: 892,
    saves: 445,
    copies: 1240,
    forks: 23,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-05T14:30:00'),
  },
  {
    id: 'prompt2',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video2.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1610206682191-c18ea65162c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGNvbG9yZnVsJTIwbW90aW9uJTIwYmx1cnxlbnwxfHx8fDE3NzU0NDAwMDh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Abstract flowing liquid colors morphing and blending in slow motion, neon pink and electric blue mixing with deep purple, high contrast lighting, macro close-up revealing intricate patterns',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['abstract', 'macro', 'slowmo'],
    cameraNotes: 'macro lens, 120fps slow motion, high-key lighting',
    moodLabel: 'Abstract',
    difficulty: 'Advanced',
    likes: 634,
    saves: 312,
    copies: 876,
    forks: 18,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-05T10:15:00'),
  },
  {
    id: 'prompt3',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video3.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1732644144489-b1974816d3c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGNpdHklMjBuaWdodCUyMGxpZ2h0c3xlbnwxfHx8fDE3NzUzNDkzMzZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Time-lapse of a bustling city intersection at night, light trails from cars creating vibrant streaks of red and white, neon signs reflecting on wet pavement, dynamic urban energy',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['urban', 'timelapse', 'motion'],
    cameraNotes: 'locked tripod, long exposure simulation, wide angle',
    moodLabel: 'Dramatic',
    difficulty: 'Beginner',
    likes: 521,
    saves: 267,
    copies: 734,
    forks: 12,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-04T18:45:00'),
  },
  {
    id: 'prompt4',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video4.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1720110701672-a2ae3a95de0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBmb3Jlc3QlMjBjaW5lbWF0aWN8ZW58MXx8fHwxNzc1NDQwMDA5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Sunlight filtering through dense forest canopy, god rays illuminating particles of dust and pollen floating in the air, gentle camera drift sideways through ancient trees',
    model: 'Kling',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['nature', 'cinematic', 'motion'],
    cameraNotes: 'gentle lateral tracking, soft diffused lighting',
    moodLabel: 'Naturalistic',
    difficulty: 'Intermediate',
    likes: 445,
    saves: 198,
    copies: 612,
    forks: 8,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-04T12:20:00'),
  },
  {
    id: 'prompt5',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video5.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1639843091483-b2564b0e477e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvY2VhbiUyMHdhdmVzJTIwc2xvdyUyMG1vdGlvbnxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Massive ocean wave cresting in ultra slow motion, water droplets suspended in air catching sunlight like diamonds, transparent turquoise water texture visible, powerful yet graceful',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['slowmo', 'nature', 'cinematic'],
    cameraNotes: 'high-speed 240fps, close-up perspective, bright daylight',
    moodLabel: 'Dramatic',
    difficulty: 'Advanced',
    likes: 1120,
    saves: 589,
    copies: 1580,
    forks: 34,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-03T16:00:00'),
  },
  {
    id: 'prompt6',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video6.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1748483720485-62a341f406e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXJyZWFsJTIwZGlnaXRhbCUyMGFydHxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Surreal dreamscape with floating geometric shapes slowly rotating in a void of pastel gradients, minimal composition, ethereal atmosphere, smooth camera orbit',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['surreal', 'abstract', 'motion'],
    cameraNotes: 'orbital camera movement, soft focus, minimal lighting',
    moodLabel: 'Surreal',
    difficulty: 'Intermediate',
    likes: 378,
    saves: 201,
    copies: 445,
    forks: 15,
    isForked: true,
    forkedFromId: 'prompt2',
    forkedFromAuthorHandle: 'soramaster',
    createdAt: new Date('2026-04-03T09:30:00'),
  },
  {
    id: 'prompt7',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video7.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529310399831-ed472b81d589?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMGZhc2hpb24lMjBtb2RlbHxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Fashion model walking towards camera in slow motion, flowing fabric billowing behind, dramatic backlighting, vertical frame composition for social media',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'portrait',
    styleTags: ['fashion', 'slowmo', 'cinematic'],
    cameraNotes: 'vertical 9:16 format, 120fps slow motion, backlit',
    moodLabel: 'Dramatic',
    difficulty: 'Intermediate',
    likes: 756,
    saves: 389,
    copies: 922,
    forks: 19,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-02T14:30:00'),
  },
  {
    id: 'prompt8',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video8.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMGRhbmNlciUyMG1vdmluZ3xlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Dancer performing fluid movements in a neon-lit studio, captured in vertical format with dynamic camera tracking, vibrant purple and blue lighting',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'portrait',
    styleTags: ['urban', 'motion', 'neon'],
    cameraNotes: 'vertical 9:16 format, tracking shot, colored gels',
    moodLabel: 'Energetic',
    difficulty: 'Advanced',
    likes: 623,
    saves: 298,
    copies: 741,
    forks: 11,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-02T10:15:00'),
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: 'workflow1',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    title: 'Luxury skincare launch thread',
    tool: 'Runway',
    description: 'A four-step workflow for building a polished product campaign from concept frames to final reveal.',
    coverVideoUrl: 'https://example.com/workflow-cover-1.mp4',
    coverThumbnailUrl: 'https://picsum.photos/seed/waltube-portrait-cover/720/1280',
    tags: ['beauty', 'cinematic', 'launch'],
    stepCount: 4,
    likes: 284,
    saves: 112,
    mediaAspectRatio: 'portrait',
    createdAt: new Date('2026-04-06T09:10:00'),
    steps: [
      {
        id: 'workflow1-step1',
        stepNumber: 1,
        label: 'Hero pour shot',
        model: 'Runway',
        generationType: 'prompt_to_video',
        promptText: 'Luxury skincare bottle rotating on wet black acrylic, warm spotlight bloom, droplets glistening, ultra-clean product cinematography, slow motion reveal.',
        note: 'Use this first to establish the premium visual language for the full sequence.',
        resultMediaUrl: 'https://example.com/workflow-step1.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-portrait-step1/720/1280',
        resultContentType: 'video',
      },
      {
        id: 'workflow1-step2',
        stepNumber: 2,
        label: 'Ingredient texture motion',
        model: 'Runway',
        generationType: 'image_to_video',
        promptText: 'Animate the serum texture with a slow orbit and glassy highlights while keeping the color palette champagne and ivory.',
        note: 'Feed a clean ingredient still as the source so the motion stays elegant.',
        inputImageUrl: 'https://picsum.photos/seed/waltube-portrait-input2/720/1280',
        resultMediaUrl: 'https://example.com/workflow-step2.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-portrait-step2/720/1280',
        resultContentType: 'video',
      },
      {
        id: 'workflow1-step3',
        stepNumber: 3,
        label: 'Cap open transition',
        model: 'Sora',
        generationType: 'frames_to_video',
        promptText:
          'Morph from capped bottle frame into uncapped bottle frame with smooth liquid motion continuity, keeping the same lens feel and warm studio lighting.',
        note: 'This works best when both frames share the same lighting setup and lens feel.',
        startFrameUrl: 'https://picsum.photos/seed/waltube-portrait-start3/720/1280',
        endFrameUrl: 'https://picsum.photos/seed/waltube-portrait-end3/720/1280',
        resultMediaUrl: 'https://example.com/workflow-step3.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-portrait-step3/720/1280',
        resultContentType: 'video',
      },
      {
        id: 'workflow1-step4',
        stepNumber: 4,
        label: 'Final still for thumbnail',
        model: 'Sora',
        generationType: 'prompt_to_image',
        promptText: 'Editorial beauty still of the bottle standing in reflective water, warm sunrise gradient, minimal luxury composition, premium skincare ad.',
        note: 'Use the final still as the social thumbnail and landing image.',
        resultMediaUrl: 'https://picsum.photos/seed/waltube-portrait-step4/720/1280',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-portrait-step4/720/1280',
        resultContentType: 'image',
      },
    ],
  },
  {
    id: 'workflow2',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    title: 'Streetwear reveal sequence',
    tool: 'Sora',
    description: 'A four-step landscape workflow to compare wide-frame thread behavior and spacing.',
    coverVideoUrl: 'https://example.com/workflow-cover-2.mp4',
    coverThumbnailUrl: 'https://picsum.photos/seed/waltube-landscape-cover/1280/720',
    tags: ['streetwear', 'urban', 'campaign'],
    stepCount: 4,
    likes: 316,
    saves: 141,
    mediaAspectRatio: 'landscape',
    createdAt: new Date('2026-04-06T11:20:00'),
    steps: [
      {
        id: 'workflow2-step1',
        stepNumber: 1,
        label: 'Wide hero reveal',
        model: 'Sora',
        generationType: 'prompt_to_video',
        promptText:
          'Wide city rooftop reveal with subject centered, wind-reactive jacket movement, dramatic skyline in the distance, golden-hour contrast.',
        note: 'Use a cinematic wide setup to establish brand tone.',
        resultMediaUrl: 'https://example.com/workflow2-step1.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-landscape-step1/1280/720',
        resultContentType: 'video',
      },
      {
        id: 'workflow2-step2',
        stepNumber: 2,
        label: 'Texture detail motion',
        model: 'Kling',
        generationType: 'image_to_video',
        promptText:
          'Animate fabric texture and logo patch with subtle camera parallax, preserving original color balance and edge details.',
        note: 'Reference still drives fine-grain material realism.',
        inputImageUrl: 'https://picsum.photos/seed/waltube-landscape-input2/1280/720',
        resultMediaUrl: 'https://example.com/workflow2-step2.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-landscape-step2/1280/720',
        resultContentType: 'video',
      },
      {
        id: 'workflow2-step3',
        stepNumber: 3,
        label: 'Pose transition',
        model: 'Sora',
        generationType: 'frames_to_video',
        promptText:
          'Transition from relaxed standing pose to walking pose with smooth body continuity and consistent rooftop lighting.',
        note: 'Keep both source frames aligned for cleaner interpolation.',
        startFrameUrl: 'https://picsum.photos/seed/waltube-landscape-start3/1280/720',
        endFrameUrl: 'https://picsum.photos/seed/waltube-landscape-end3/1280/720',
        resultMediaUrl: 'https://example.com/workflow2-step3.mp4',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-landscape-step3/1280/720',
        resultContentType: 'video',
      },
      {
        id: 'workflow2-step4',
        stepNumber: 4,
        label: 'Final poster still',
        model: 'Pika',
        generationType: 'prompt_to_image',
        promptText:
          'Landscape editorial still with bold streetwear silhouette, clean sky gradient, and minimal text-safe composition.',
        note: 'Use as cover and campaign endpoint visual.',
        resultMediaUrl: 'https://picsum.photos/seed/waltube-landscape-step4/1280/720',
        resultThumbnailUrl: 'https://picsum.photos/seed/waltube-landscape-step4/1280/720',
        resultContentType: 'image',
      },
    ],
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif1',
    userId: 'currentUser',
    type: 'follow',
    fromUid: 'user1',
    fromHandle: 'soramaster',
    fromAvatar: mockUsers[0].avatarUrl,
    message: '@soramaster started following you',
    read: false,
    createdAt: new Date('2026-04-06T08:30:00'),
  },
  {
    id: 'notif2',
    userId: 'currentUser',
    type: 'like',
    fromUid: 'user2',
    fromHandle: 'runwaypro',
    fromAvatar: mockUsers[1].avatarUrl,
    promptId: 'prompt1',
    message: '@runwaypro liked your prompt',
    read: false,
    createdAt: new Date('2026-04-05T22:15:00'),
  },
  {
    id: 'notif3',
    userId: 'currentUser',
    type: 'like',
    fromUid: 'user1',
    fromHandle: 'soramaster',
    fromAvatar: mockUsers[0].avatarUrl,
    promptId: 'prompt1',
    message: '@soramaster liked your prompt',
    read: true,
    createdAt: new Date('2026-04-05T16:45:00'),
  },
  {
    id: 'notif4',
    userId: 'currentUser',
    type: 'fork',
    fromUid: 'user2',
    fromHandle: 'runwaypro',
    fromAvatar: mockUsers[1].avatarUrl,
    promptId: 'prompt1',
    message: '@runwaypro forked your prompt',
    read: true,
    createdAt: new Date('2026-04-04T14:20:00'),
  },
];

export const mockCollections: Collection[] = [
  {
    id: 'collection1',
    userId: 'currentUser',
    name: 'Cinematic',
    description: 'Epic, filmic shots to revisit later.',
    count: 24,
    thumbnails: mockPrompts.slice(0, 4).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-04-01T08:00:00'),
  },
  {
    id: 'collection2',
    userId: 'currentUser',
    name: 'Nature',
    description: 'Landscapes and outdoor motion references.',
    count: 18,
    thumbnails: mockPrompts.slice(1, 5).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-03-28T08:00:00'),
  },
  {
    id: 'collection3',
    userId: 'currentUser',
    name: 'Abstract',
    description: 'Stylized motion and texture ideas.',
    count: 12,
    thumbnails: mockPrompts.slice(2, 6).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-03-20T08:00:00'),
  },
];

