[package]
name = "waltube_premium"
edition = "2024.beta" # edition = "2024.beta" also works, but 2024.beta is recommended
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
waltube_premium = "0x0"
